                                                                                                                                                                                                                                                                                      import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  app1: [{type: 'autogenerated', dirName: 'app1'}],
  app2: [{type: 'autogenerated', dirName: 'app2'}],
  frontend: [{type: 'autogenerated', dirName: 'frontend'}],
  backend: [

        {type: 'doc', id: 'backend/index'}, 
        {
          type: 'category',
          label: 'Pytest', 
          items: [
            {type: 'autogenerated', dirName: 'backend/pytest'},  
          ],
          collapsed: true,  
        },
        {
          type: 'category',
          label: 'HTTPX',  
          items: [
            {type: 'autogenerated', dirName: 'backend/httpx'},  
          ],
          collapsed: true,  
        },
        {
          type: 'category',
          label: 'Unittest', 
          items: [
            {type: 'autogenerated', dirName: 'backend/unittest'}, 
          ],
          collapsed: true,  
        },
       
      
        {type: 'doc', id: 'backend/comparison'}, 
      ],
    
};

export default sidebars;
