                                                                                                                                                                                                                                                                                      import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {

  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  app1:[{type:'autogenerated', dirName: 'app1'}],
  app2:[{type:'autogenerated', dirName: 'app2'}],
  frontend:[{type:'autogenerated', dirName: 'frontend'}],
  backend:[{type:'autogenerated', dirName: 'backend'}],
  // backend:[
  //   {
  //     type:'category',
  //     label:'Backend',
  //     items:[{type:'autogenerated', dirName: 'backend'}],
  //     collapsed:true,
  //   },
  // ],

};

export default sidebars;
